services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command:
      - "-js"
      - "-sd"
      - "/data"
    volumes:
      - ./nats-data:/data
    restart: unless-stopped
    networks:
      - mailservice-net

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NATS_URL=nats://nats:4222
    restart: unless-stopped
    depends_on:
      - nats
    networks:
      - mailservice-net

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - NATS_URL=nats://nats:4222
      - TENANT_ID=857a7b86-2d66-46f2-92e1-25be0c27e398
      - CLIENT_ID=84e5a7cb-6a66-4133-ba85-43a1eaf95baf
      - CLIENT_SECRET=Ze38Q~8jSUXiHbMSOqPzcAgbubdD-eHVUw8QDaG9
      - SENDER_EMAIL=EIT_qualitaetsreport@edeka.de
    restart: unless-stopped
    depends_on:
      - nats
    deploy:
      replicas: 1
    networks:
      - mailservice-net

networks:
  mailservice-net:
    driver: bridge
